// SproutCore ViewBuilder Design Format v1.0
// WARNING: This file is automatically generated.  DO NOT EDIT.  Changes you
// make to this file will be lost.
Green.mainPage = SC.Page.design({
  mainPane: SC.MainPane.design({
    childViews: [SC.LabelView.design({
      layout: {
        "left": 110,
        "width": 200,
        "top": 20,
        "height": 18
      },
      value: "Welcome to SproutCore!"
    }), SC.LabelView.design({
      layout: {
        "left": 47,
        "width": 199,
        "top": 111,
        "height": 33
      }
    }), SC.TextFieldView.design({
      layout: {
        "left": 106,
        "width": 78,
        "top": 64,
        "height": 29
      }
    })]
  }),
  sidePane: SC.Pane.design({}),
  pageName: "Green.mainPage"
});
